spring:
  application:
    name: "@app-name@"

application:
  version: "@version@"

ratpack-extra:
  path-to-static-content: "@path-to-static-content@"




list[0].url =
list[0].descr =

list[1].url =
list[1].descr =